# Generated by Django 4.0 on 2022-01-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_starting_pid_listing_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
