# Generated by Django 4.0 on 2022-01-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(blank=True, to='auctions.Comments'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user_name',
            field=models.CharField(max_length=64),
        ),
    ]
