# Generated by Django 4.0 on 2022-01-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_last_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='last_bidder',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='user_name',
        ),
    ]
