# Generated by Django 4.0 on 2022-01-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listing_last_bidder_remove_listing_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='last_bidder',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='user_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
