# Generated by Django 4.0 on 2022-01-22 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_last_bidder_listing_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='last_bidder',
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biders', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('last_bidder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_bidder', to='auctions.user')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
            ],
        ),
    ]
