# Generated by Django 4.0 on 2022-01-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_listing_last_bidder_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='user_name',
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
        ),
    ]
