# Generated by Django 4.0 on 2022-01-22 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_listing_user_name_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='biders',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='last_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_bidder', to='auctions.user'),
        ),
    ]
