# Generated by Django 4.0 on 2022-01-22 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_bid_biders_alter_bid_last_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='biders',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
