# Generated by Django 4.0 on 2022-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_comments_user_name_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='listings',
            field=models.ManyToManyField(blank=True, to='auctions.Listing'),
        ),
    ]
