# Generated by Django 4.0 on 2022-01-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='last_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_bidder', to='auctions.user'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
        ),
    ]
